//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Operation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserType
    {
        public int UserTypeId { get; set; }
        public string UserType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
